name: Deploy with Docker-Compose

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, local-docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with docker-compose
        run: |
          cd /home/abdelrahman-alzyoud/Desktop/ZYOUD/DevOps/OPTIMUM---DevOps-TASKS/CI.CD/
          docker compose up -d --build

